# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET 8 application.

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

env:
  Configuration: Release
  Project: "**/*.csproj"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration $Configuration
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ${{ Project }} --no-restore --no-build --configuration $Configuration --output ${{ github.workspace }}/publish
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: carsties-microservices
        path:  ${{ github.workspace }}/publish
        overwrite: true
